// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD42EwoXVXeOcy9wzEb3lL8_I2LtdVtV6s',
    appId: '1:431279332930:web:2d608f303fe0ca3fa257db',
    messagingSenderId: '431279332930',
    projectId: 'test-b1a5c',
    authDomain: 'test-b1a5c.firebaseapp.com',
    storageBucket: 'test-b1a5c.appspot.com',
    measurementId: 'G-8YNPDGM9R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDIA_5ZuUftq0Hj_DjZxsUSLSFRY111vY',
    appId: '1:431279332930:android:ff4bf9b349501f62a257db',
    messagingSenderId: '431279332930',
    projectId: 'test-b1a5c',
    storageBucket: 'test-b1a5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8eqM1tXhvcDHaf74Dxn95BAU1uJnQubg',
    appId: '1:431279332930:ios:e1f181b94336f1f0a257db',
    messagingSenderId: '431279332930',
    projectId: 'test-b1a5c',
    storageBucket: 'test-b1a5c.appspot.com',
    iosBundleId: 'com.example.testdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8eqM1tXhvcDHaf74Dxn95BAU1uJnQubg',
    appId: '1:431279332930:ios:e1f181b94336f1f0a257db',
    messagingSenderId: '431279332930',
    projectId: 'test-b1a5c',
    storageBucket: 'test-b1a5c.appspot.com',
    iosBundleId: 'com.example.testdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD42EwoXVXeOcy9wzEb3lL8_I2LtdVtV6s',
    appId: '1:431279332930:web:f48b0972305cfa99a257db',
    messagingSenderId: '431279332930',
    projectId: 'test-b1a5c',
    authDomain: 'test-b1a5c.firebaseapp.com',
    storageBucket: 'test-b1a5c.appspot.com',
    measurementId: 'G-0F6FJ8W412',
  );
}
